# Generated by Django 4.2.3 on 2023-09-26 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=30)),
                ('confirm_password', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isPayment', models.BooleanField(default=False)),
                ('payment_mode', models.CharField(default='BLT', max_length=3)),
                ('date_expired', models.BooleanField(default=False)),
                ('client_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_account', to='rest.client')),
            ],
        ),
    ]
