# Generated by Django 4.2.3 on 2023-09-27 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='confirm_password',
        ),
    ]
