# Generated by Django 4.2.3 on 2023-09-29 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0002_remove_client_confirm_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='clients/'),
        ),
    ]
