# Generated by Django 4.2.3 on 2023-09-21 16:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dashboard', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('description', models.TextField()),
                ('photo', models.ImageField(null=True, upload_to='Authors/')),
            ],
            options={
                'ordering': ['name', 'description'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Comic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True)),
                ('description', models.TextField()),
                ('type', models.CharField(choices=[('MH', 'Manhuas'), ('WT', 'Webtoons'), ('NV', 'Novels'), ('MG', 'Mangas'), ('HQ', "HQ's")], default='MH', max_length=40)),
                ('copyright', models.TextField()),
                ('old_min', models.IntegerField(default=12)),
                ('stars', models.IntegerField(default=0)),
                ('image_front_book', models.ImageField(null=True, upload_to='image_front_books')),
                ('image_back_book', models.ImageField(null=True, upload_to='image_back_books')),
                ('year_pub', models.CharField(max_length=4)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('authors', models.ManyToManyField(to='comic.author')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='comic.category')),
            ],
            options={
                'ordering': ['name', 'description', 'copyright', 'year_pub'],
            },
        ),
        migrations.CreateModel(
            name='Editor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('description', models.TextField()),
                ('photo', models.ImageField(null=True, upload_to='Editors/')),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='ReadComics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comics', models.ManyToManyField(null=True, to='comic.comic')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MyList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comics', models.ManyToManyField(null=True, to='comic.comic')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='comic',
            name='editor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='comic.editor'),
        ),
        migrations.AddField(
            model_name='comic',
            name='episodes',
            field=models.ManyToManyField(null=True, to='episode.episode'),
        ),
        migrations.AddField(
            model_name='comic',
            name='sub_category',
            field=models.ManyToManyField(max_length=3, null=True, to='comic.subcategory'),
        ),
    ]
