# Generated by Django 4.2.3 on 2023-09-21 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('episode', '0001_initial'),
        ('comic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comic',
            name='episodes',
            field=models.ManyToManyField(null=True, to='episode.episode'),
        ),
    ]
