# Generated by Django 4.2.3 on 2023-09-29 22:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0002_remove_client_confirm_password'),
        ('comic', '0002_alter_comic_episodes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mylist',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rest.client'),
        ),
        migrations.AlterField(
            model_name='readcomics',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rest.client'),
        ),
    ]
