# Generated by Django 4.2.3 on 2023-10-11 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comic', '0004_comic_image_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('photo', models.ImageField(upload_to='notices')),
            ],
        ),
        migrations.AddField(
            model_name='comic',
            name='notices',
            field=models.ManyToManyField(related_name='notices', to='comic.notice'),
        ),
    ]
