# Generated by Django 4.2.3 on 2023-10-17 21:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comic', '0005_notice_comic_notices'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comic',
            name='sub_category',
        ),
        migrations.AddField(
            model_name='comic',
            name='sub_category',
            field=models.ForeignKey(max_length=3, null=True, on_delete=django.db.models.deletion.CASCADE, to='comic.subcategory'),
        ),
    ]
