# Generated by Django 4.2.3 on 2023-10-17 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comic', '0006_remove_comic_sub_category_comic_sub_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='functions',
            field=models.CharField(choices=[('WR', 'writer'), ('PT', 'painter')], default='WR', max_length=2),
        ),
    ]
