# Generated by Django 4.2.3 on 2023-10-31 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comic', '0008_alter_author_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreviewComics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comics', models.ManyToManyField(blank=True, related_name='comics', to='comic.comic')),
            ],
        ),
    ]
