# Generated by Django 4.2.3 on 2023-10-31 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comic', '0009_previewcomics'),
    ]

    operations = [
        migrations.AddField(
            model_name='previewcomics',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
