# Generated by Django 4.2.3 on 2023-10-31 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comic', '0010_previewcomics_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='comic',
            name='preview_reader',
            field=models.BooleanField(default=False),
        ),
    ]
