# Generated by Django 4.2.3 on 2023-11-01 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('episode', '0007_alter_episode_created_at'),
        ('comic', '0011_comic_preview_reader'),
    ]

    operations = [
        migrations.CreateModel(
            name='DisLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='comic',
            name='episodes',
            field=models.ManyToManyField(blank=True, null=True, to='episode.episode'),
        ),
        migrations.AlterField(
            model_name='comic',
            name='notices',
            field=models.ManyToManyField(blank=True, related_name='notices', to='comic.notice'),
        ),
    ]
