# Generated by Django 4.2.3 on 2023-11-01 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('episode', '0015_alter_episode_created_at'),
        ('comic', '0014_dislike_client_dislike_comic_alter_like_client_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comic',
            name='episodes',
            field=models.ManyToManyField(blank=True, to='episode.episode'),
        ),
        migrations.AlterField(
            model_name='mylist',
            name='comics',
            field=models.ManyToManyField(to='comic.comic'),
        ),
        migrations.AlterField(
            model_name='readcomics',
            name='comics',
            field=models.ManyToManyField(to='comic.comic'),
        ),
    ]
