# Generated by Django 4.2.3 on 2023-11-07 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comic', '0018_comic_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='link',
            field=models.URLField(null=True),
        ),
    ]
