# Generated by Django 4.2.3 on 2023-10-31 17:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('episode', '0003_remove_episode_qt_by_page_alter_episode_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='created_at',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2023, 10, 31, 17, 44, 27, 929559, tzinfo=datetime.timezone.utc)),
        ),
    ]
