# Generated by Django 4.2.3 on 2023-11-02 22:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('episode', '0017_alter_episode_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='created_at',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2023, 11, 2, 22, 8, 36, 871410, tzinfo=datetime.timezone.utc)),
        ),
    ]
